import { z } from 'zod';

export const scholarshipSchema = z.object({
  aadhar: z.string().regex(/^\d{12}$/, 'Aadhar number must be exactly 12 digits'),
  religion: z.string().min(1, 'Religion is required'),
  community: z.enum(['SC', 'ST', 'OBC', 'General'], { errorMap: () => ({ message: 'Please enter SC, ST, OBC, or General only' }) }),
  fatherName: z.string().regex(/^[a-zA-Z ]+$/, "Father's Name must contain alphabets and spaces only").max(100),
  motherName: z.string().regex(/^[a-zA-Z ]+$/, "Mother's Name must contain alphabets and spaces only").max(100),
  annualIncome: z.coerce.number({ invalid_type_error: 'Required' }).min(0, 'Cannot be negative').max(99999999, 'Must be less than 99,999,999'),
  instituteCode: z.string().min(1, 'Institute Code is required'),
  instituteName: z.string().min(1, 'Institute Name is required'),
  presentClass: z.string().min(1, 'Present Class is required'),
  classYear: z.string().min(1, 'Class Year is required'),
  modeOfStudy: z.string().min(1, 'Mode of Study is required'),
  classStartDate: z.string().min(1, 'Start Date is required'),
  prevClass: z.string().optional(),
  prevPassYear: z.string().optional(),
  prevClassPercent: z.union([z.coerce.number().min(0).max(99, 'Percentage must be between 0 and 99'), z.literal('')]).optional(),
  roll10: z.string().regex(/^\d{8}$/, 'Roll Number must be exactly 8 digits'),
  board10: z.string().min(1, 'Board Name is required'),
  year10: z.string().min(1, 'Passing Year is required'),
  percent10: z.coerce.number().min(0).max(99, 'Percentage must be between 0 and 99'),
  roll12: z.union([z.string().regex(/^\d{8}$/, 'Roll Number must be exactly 8 digits'), z.literal('')]).optional(),
  board12: z.string().optional(),
  year12: z.string().optional(),
  percent12: z.union([z.coerce.number().min(0).max(99, 'Percentage must be between 0 and 99'), z.literal('')]).optional(),
  admissionFee: z.coerce.number().min(0).max(99999, 'Fee must be between 0 and 99,999'),
  tuitionFee: z.coerce.number().min(0).max(99999, 'Fee must be between 0 and 99,999'),
  otherFee: z.union([z.coerce.number().min(0).max(99999, 'Fee must be between 0 and 99,999'), z.literal('')]).optional(),
  isDisabled: z.enum(['Yes', 'No']),
  disabilityType: z.string().max(100).optional(),
  disabilityPercent: z.union([z.coerce.number().min(0).max(100, 'Must be between 0 and 100'), z.literal('')]).optional(),
  maritalStatus: z.string().optional(),
  parentsProfession: z.string().max(100).optional(),
  contactState: z.string().min(1, 'State is required'),
  contactDistrict: z.string().min(1, 'District is required'),
  contactBlock: z.string().optional(),
  houseNo: z.union([z.string().regex(/^\d+[a-zA-Z]?$/, 'Format: e.g. 49, 228C'), z.literal('')]).optional(),
  streetNo: z.union([z.string().regex(/^\d{2}$/, 'Must be exactly 2 digits'), z.literal('')]).optional(),
  pincode: z.string().regex(/^\d{6}$/, 'Pincode must be exactly 6 digits'),
  scheme: z.string().min(1, 'Scheme is required'),
  agree: z.literal(true, { errorMap: () => ({ message: 'Please accept the declaration' }) })
});